<?php
header("Content-Type: application/download\n");
header("Content-Disposition: attachment; filename=\"Data Buku Induk.xls\"");
header("Content-Transfer-Encoding: binary");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Pragma: public");
?>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="Buku%20Induk%20Lagi_files/filelist.xml">
<style id="Pendaftar lolos PPDB (UN)_1475_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl631475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl641475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:general;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl651475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:general;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl661475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl671475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Pendaftar lolos PPDB (UN)_1475" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1768 class=xl631475
 style='border-collapse:collapse;table-layout:fixed;width:1327pt'>
 <col class=xl631475 width=37 style='mso-width-source:userset;mso-width-alt:
 1353;width:28pt'>
 <col class=xl631475 width=122 span=2 style='mso-width-source:userset;
 mso-width-alt:4461;width:92pt'>
 <col class=xl631475 width=87 style='mso-width-source:userset;mso-width-alt:
 3181;width:65pt'>
 <col class=xl631475 width=179 style='mso-width-source:userset;mso-width-alt:
 6546;width:134pt'>
 <col class=xl631475 width=123 style='mso-width-source:userset;mso-width-alt:
 4498;width:92pt'>
 <col class=xl631475 width=113 style='mso-width-source:userset;mso-width-alt:
 4132;width:85pt'>
 <col class=xl631475 width=115 style='mso-width-source:userset;mso-width-alt:
 4205;width:86pt'>
 <col class=xl631475 width=231 style='mso-width-source:userset;mso-width-alt:
 8448;width:173pt'>
 <col class=xl631475 width=67 style='mso-width-source:userset;mso-width-alt:
 2450;width:50pt'>
 <col class=xl631475 width=64 style='width:48pt'>
 <col class=xl631475 width=78 span=2 style='mso-width-source:userset;
 mso-width-alt:2852;width:59pt'>
 <col class=xl631475 width=77 style='mso-width-source:userset;mso-width-alt:
 2816;width:58pt'>
 <col class=xl631475 width=83 style='mso-width-source:userset;mso-width-alt:
 3035;width:62pt'>
 <col class=xl631475 width=64 span=3 style='width:48pt'>
 <tr height=27 style='mso-height-source:userset;height:20.25pt'>
  <td height=27 class=xl631475 width=37 style='height:20.25pt;width:28pt'></td>
  <td class=xl631475 width=122 style='width:92pt'></td>
  <td class=xl631475 width=122 style='width:92pt'></td>
  <td class=xl631475 width=87 style='width:65pt'></td>
  <td class=xl631475 width=179 style='width:134pt'></td>
  <td class=xl631475 width=123 style='width:92pt'></td>
  <td class=xl631475 width=113 style='width:85pt'></td>
  <td class=xl631475 width=115 style='width:86pt'></td>
  <td class=xl631475 width=231 style='width:173pt'></td>
  <td class=xl631475 width=67 style='width:50pt'></td>
  <td class=xl631475 width=64 style='width:48pt'></td>
  <td class=xl631475 width=78 style='width:59pt'></td>
  <td class=xl631475 width=78 style='width:59pt'></td>
  <td class=xl631475 width=77 style='width:58pt'></td>
  <td class=xl631475 width=83 style='width:62pt'></td>
  <td class=xl631475 width=64 style='width:48pt'></td>
  <td class=xl631475 width=64 style='width:48pt'></td>
  <td class=xl631475 width=64 style='width:48pt'></td>
 </tr>
 <tr height=28 style='mso-height-source:userset;height:21.0pt'>
  <td height=28 class=xl661475 width=37 style='height:21.0pt;width:28pt'>No</td>
  <td class=xl661475 width=122 style='border-left:none;width:92pt'>Tahun
  Angkatan</td>
  <td class=xl661475 width=122 style='border-left:none;width:92pt'>NIS</td>
  <td class=xl661475 width=87 style='border-left:none;width:65pt'>NISN</td>
  <td class=xl661475 width=179 style='border-left:none;width:134pt'>Nama</td>
  <td class=xl661475 width=123 style='border-left:none;width:92pt'>Jenis
  Kelamin</td>
  <td class=xl661475 width=113 style='border-left:none;width:85pt'>Tempat Lahir</td>
  <td class=xl661475 width=115 style='border-left:none;width:86pt'>Tanggal
  Lahir</td>
  <td class=xl661475 width=231 style='border-left:none;width:173pt'>Alamat</td>
  <td class=xl661475 width=67 style='border-left:none;width:50pt'>Status</td>
  <td class=xl671475 width=64 style='width:48pt'></td>
  <td class=xl671475 width=78 style='width:59pt'></td>
  <td class=xl671475 width=78 style='width:59pt'></td>
  <td class=xl671475 width=77 style='width:58pt'></td>
  <td class=xl671475 width=83 style='width:62pt'></td>
  <td class=xl671475 width=64 style='width:48pt'></td>
  <td class=xl671475 width=64 style='width:48pt'></td>
  <td class=xl671475 width=64 style='width:48pt'></td>
 </tr>
 <?php 
  $i=1;
  foreach ($tabel_siswa as $row) {
  ?>
 <tr height=63 style='height:47.25pt'>
  <td height=63 class=xl641475 width=37 style='height:47.25pt;border-top:none;
  width:28pt'><?php echo $i; ?></td>
  <td class=xl641475 width=122 style='border-top:none;border-left:none;
  width:92pt'><?php echo $row->tahun_ajaran; ?></td>
  <td class=xl641475 width=122 style='border-top:none;border-left:none;
  width:92pt'><?php echo $row->no_induk_siswa; ?></td>
  <td class=xl641475 width=87 style='border-top:none;border-left:none;
  width:65pt'><?php echo $row->nisn; ?></td>
  <td class=xl641475 width=179 style='border-top:none;border-left:none;
  width:134pt'><?php echo $row->nama; ?></td>
  <td class=xl641475 width=123 style='border-top:none;border-left:none;
  width:92pt'><?php echo $row->jenis_kelamin; ?></td>
  <td class=xl641475 width=113 style='border-top:none;border-left:none;
  width:85pt'><?php echo $row->tempat_lahir; ?></td>
  <td class=xl641475 width=115 style='border-top:none;border-left:none;
  width:86pt'><?php echo $row->tanggal_lahir; ?></td>
  <td class=xl641475 width=231 style='border-top:none;border-left:none;
  width:173pt'><?php echo $row->alamat; ?></td>
  <td class=xl641475 width=67 style='border-top:none;border-left:none;
  width:50pt'><?php echo $row->status_siswa; ?></td>
  <td class=xl651475 width=64 style='width:48pt'></td>
  <td class=xl651475 width=78 style='width:59pt'></td>
  <td class=xl651475 width=78 style='width:59pt'></td>
  <td class=xl651475 width=77 style='width:58pt'></td>
  <td class=xl651475 width=83 style='width:62pt'></td>
  <td class=xl651475 width=64 style='width:48pt'></td>
  <td class=xl651475 width=64 style='width:48pt'></td>
  <td class=xl651475 width=64 style='width:48pt'></td>
 </tr>
 <?php
 $i=$i+1;
            }
            ?>
 <tr class=xl671475 height=21 style='height:15.75pt'>
  <td height=21 class=xl671475 width=37 style='height:15.75pt;width:28pt'></td>
  <td class=xl631475 width=122 style='width:92pt'></td>
  <td class=xl631475 width=122 style='width:92pt'></td>
  <td class=xl631475 width=87 style='width:65pt'></td>
  <td class=xl631475 width=179 style='width:134pt'></td>
  <td class=xl631475 width=123 style='width:92pt'></td>
  <td class=xl631475 width=113 style='width:85pt'></td>
  <td class=xl631475 width=115 style='width:86pt'></td>
  <td class=xl631475 width=231 style='width:173pt'></td>
  <td class=xl631475 width=67 style='width:50pt'></td>
  <td class=xl631475 width=64 style='width:48pt'></td>
  <td class=xl631475 width=78 style='width:59pt'></td>
  <td class=xl631475 width=78 style='width:59pt'></td>
  <td class=xl631475 width=77 style='width:58pt'></td>
  <td class=xl631475 width=83 style='width:62pt'></td>
  <td class=xl631475 width=64 style='width:48pt'></td>
  <td class=xl631475 width=64 style='width:48pt'></td>
  <td class=xl631475 width=64 style='width:48pt'></td>
 </tr>
 <tr class=xl651475 height=46 style='mso-height-source:userset;height:34.5pt'>
  <td height=46 class=xl631475 width=37 style='height:34.5pt;width:28pt'></td>
  <td class=xl631475 width=122 style='width:92pt'></td>
  <td class=xl631475 width=122 style='width:92pt'></td>
  <td class=xl631475 width=87 style='width:65pt'></td>
  <td class=xl631475 width=179 style='width:134pt'></td>
  <td class=xl631475 width=123 style='width:92pt'></td>
  <td class=xl631475 width=113 style='width:85pt'></td>
  <td class=xl631475 width=115 style='width:86pt'></td>
  <td class=xl631475 width=231 style='width:173pt'></td>
  <td class=xl631475 width=67 style='width:50pt'></td>
  <td class=xl631475 width=64 style='width:48pt'></td>
  <td class=xl631475 width=78 style='width:59pt'></td>
  <td class=xl631475 width=78 style='width:59pt'></td>
  <td class=xl631475 width=77 style='width:58pt'></td>
  <td class=xl631475 width=83 style='width:62pt'></td>
  <td class=xl631475 width=64 style='width:48pt'></td>
  <td class=xl631475 width=64 style='width:48pt'></td>
  <td class=xl651475 width=64 style='width:48pt'></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=37 style='width:28pt'></td>
  <td width=122 style='width:92pt'></td>
  <td width=122 style='width:92pt'></td>
  <td width=87 style='width:65pt'></td>
  <td width=179 style='width:134pt'></td>
  <td width=123 style='width:92pt'></td>
  <td width=113 style='width:85pt'></td>
  <td width=115 style='width:86pt'></td>
  <td width=231 style='width:173pt'></td>
  <td width=67 style='width:50pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=78 style='width:59pt'></td>
  <td width=78 style='width:59pt'></td>
  <td width=77 style='width:58pt'></td>
  <td width=83 style='width:62pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
