<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<?php
header("Content-Type: application/download\n");
header("Content-Disposition: attachment; filename=\"Data Lengkap Siswa.xls\"");
header("Content-Transfer-Encoding: binary");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Pragma: public");
?>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="data%20lengkap%20siswa%20lengkap_files/filelist.xml">
<style id="data lengkap siswa dari buku induk_14478_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl1514478
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6314478
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6414478
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="data lengkap siswa dari buku induk_14478" align=center
x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=484 style='border-collapse:
 collapse;table-layout:fixed;width:363pt'>
 <col width=229 style='mso-width-source:userset;mso-width-alt:8374;width:172pt'>
 <col width=255 style='mso-width-source:userset;mso-width-alt:9325;width:191pt'>
 <tr height=20 style='height:15.0pt'>
  <td colspan=2 height=20 class=xl6314478 width=484 style='height:15.0pt;
  width:363pt'>Data Lengkap Siswa</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'></td>
  <td class=xl6414478></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nama</td>
  <td class=xl6414478><?php echo $row_siswa->nama; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>NIS</td>
  <td class=xl6414478><?php echo $row_siswa->no_induk_siswa; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>NISN</td>
  <td class=xl6414478><?php echo $row_siswa->nisn; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Jenis Kelamin</td>
  <td class=xl6414478><?php echo $row_siswa->jenis_kelamin; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Tempat Lahir</td>
  <td class=xl6414478><?php echo $row_siswa->tempat_lahir; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Tanggal Lahir</td>
  <td class=xl6414478><?php echo $row_siswa->tanggal_lahir; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Agama</td>
  <td class=xl6414478><?php echo $row_siswa->agama; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Berkebutuhan Khusus</td>
  <td class=xl6414478><?php echo $row_siswa->berkebutuhan_khusus; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Alamat</td>
  <td class=xl6414478><?php echo $row_siswa->alamat; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>RT</td>
  <td class=xl6414478><?php echo $row_siswa->rt; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>RW</td>
  <td class=xl6414478><?php echo $row_siswa->rw; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nama Dusun</td>
  <td class=xl6414478><?php echo $row_siswa->nama_dusun; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Desa Kelurahan</td>
  <td class=xl6414478><?php echo $row_siswa->desa_kelurahan; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Kecamatan</td>
  <td class=xl6414478><?php echo $row_siswa->kecamatan; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Kode Pos</td>
  <td class=xl6414478><?php echo $row_siswa->kode_pos; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Tempat Tinggal</td>
  <td class=xl6414478><?php echo $row_siswa->tempat_tinggal; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Kategori penduduk</td>
  <td class=xl6414478><?php echo $row_siswa->kategori_penduduk; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Transportasi</td>
  <td class=xl6414478><?php echo $row_siswa->transportasi; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nomor telepon</td>
  <td class=xl6414478><?php echo $row_siswa->no_telepon; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Email</td>
  <td class=xl6414478><?php echo $row_siswa->email; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nama SD/ MI</td>
  <td class=xl6414478><?php echo $row_siswa->nama_sd_mi; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Asal Mutasi</td>
  <td class=xl6414478><?php echo $row_siswa->asal_mutasi; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Lama Belajar di SD/MI</td>
  <td class=xl6414478><?php echo $row_siswa->lama_belajar_disd_mi; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Pernah PAUD</td>
  <td class=xl6414478><?php echo $row_siswa->pernah_paud; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Pernah TK</td>
  <td class=xl6414478><?php echo $row_siswa->pernah_tk; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>No Seri SKHUN sementara</td>
  <td class=xl6414478><?php echo $row_siswa->no_seri_skhun_s; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>No Seri Ijazah SD/MI</td>
  <td class=xl6414478><?php echo $row_siswa->no_seri_ijazah_sd_mi; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>No Seri SKHUN<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl6414478><?php echo $row_siswa->no_skhun_mi; ?><span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nilai Ujian Nasional</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nilai Matematika</td>
  <td class=xl6414478><?php echo $row_siswa->nilai_un_mat; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nilai B.Indonesia</td>
  <td class=xl6414478><?php echo $row_siswa->nilai_un_ind; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nilai IPA</td>
  <td class=xl6414478><?php echo $row_siswa->nilai_un_ipa; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nilai Prestasi</td>
  <td class=xl6414478><?php echo $row_siswa->nilai_prestasi; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Total Nilai</td>
  <td class=xl6414478><?php echo $row_siswa->nilai_un_nun; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Penerima KPS/ KKS/ PKH/
  KIP</td>
  <td class=xl6414478><?php echo $row_siswa->penerima_kps_kks_pkh_kip; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nomor penerima</td>
  <td class=xl6414478><?php echo $row_siswa->no_penerima; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Anak ke</td>
  <td class=xl6414478><?php echo $row_siswa->anak_ke; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Jumlah saudara kandung</td>
  <td class=xl6414478><?php echo $row_siswa->jumlah_saudara_kandung; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>jumlah saudara tiri</td>
  <td class=xl6414478><?php echo $row_siswa->jumlah_saudara_tiri; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>jumlah saudara angkat</td>
  <td class=xl6414478><?php echo $row_siswa->jumlah_saudara_angkat; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Status dalam keluarga</td>
  <td class=xl6414478><?php echo $row_siswa->status_dalam_keluarga; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Pernah Menderita sakit</td>
  <td class=xl6414478><?php echo $row_siswa->pernah_menderita_sakit; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Pernah mengaji</td>
  <td class=xl6414478><?php echo $row_siswa->pernah_mengaji; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Keterangan mengaji</td>
  <td class=xl6414478><?php echo $row_siswa->keterangan_mengaji; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Anak yatim piatu</td>
  <td class=xl6414478><?php echo $row_siswa->anak_yatim_piatu; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Bahasa sehari hari
  dirumah</td>
  <td class=xl6414478><?php echo $row_siswa->bahasa_sehari_hari_dirumah; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Status siswa</td>
  <td class=xl6414478><?php echo $row_siswa->status_siswa; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Tinggi badan</td>
  <td class=xl6414478><?php echo $row_siswa->tinggi_badan; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Berat badan</td>
  <td class=xl6414478><?php echo $row_siswa->berat_badan; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Hobi</td>
  <td class=xl6414478><?php echo $row_siswa->hobi; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'></td>
  <td class=xl6414478></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=2 height=20 class=xl6314478 style='height:15.0pt'>Data Lengkap
  Orangtua</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'></td>
  <td class=xl6414478></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nama Ayah</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->nama_ayah; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Gelar depan</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->gelar_depan_ayah; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Gelar belakang</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->gelar_belakang_ayah; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Tempat lahir</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->tempat_lahir_ayah; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Tanggal lahir</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->tanggal_lahir_ayah; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Kewarganegaraan</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->kewarganegaraan_ayah; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Agama</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->agama_ayah; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Pendidikan</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->pendidikan_ayah; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Pekerjaan</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->pekerjaan_ayah; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Penghasilan</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->penghasilan_ayah; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Berkebutuhan khusus</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->ayah_berkebutuhan_khusus; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nomor telepon</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->no_telepon_hp_ayah; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'></td>
  <td class=xl6414478></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nama Ibu</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->nama_ibu; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Gelar depan</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->gelar_depan_ibu; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Gelar belakang</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->gelar_belakang_ibu; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Tempat lahir</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->tempat_lahir_ibu; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Tanggal lahir</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->tanggal_lahir_ibu; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Kewarganegaraan</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->kewarganegaraan_ibu; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Agama</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->agama_ibu; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Pendidikan</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->pendidikan_ibu; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Pekerjaan</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->pekerjaan_ibu; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Penghasilan</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->penghasilan_ibu; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Berkebutuhan khusus</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->ibu_berkebutuhan_khusus; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nomor telepon</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->nomor_telepon_ibu; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'></td>
  <td class=xl6414478></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nama wali</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->nama_wali; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Tempat lahir</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->tempat_lahir_wali; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Tanggal lahir</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->tanggal_lahir_wali; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Pendidikan wali</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->pendidikan_wali; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Kewarganegaraan<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl6414478><?php echo $row_siswa_ortu->kewarganegaraan_wali; ?><span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Agama</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->agama_wali; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Pekerjaan</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->pekerjaan_wali; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Penghasilan</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->penghasilan_wali; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Alamat</td>
  <td class=xl6414478><?php echo $row_siswa_ortu->alamat_wali; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6414478 style='height:15.0pt'>Nomor telepon<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl6414478><?php echo $row_siswa_ortu->no_telepon_hp_wali; ?><span style='mso-spacerun:yes'> </span></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=229 style='width:172pt'></td>
  <td width=255 style='width:191pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
